language: python
python:
  - "3.8"

# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install -E sphinx

# command to run tests
script:
  - pytest